name: "csteach424"
subname: "Client-Side Web Design"
description: "a collection of resources for COMP 424..."

url: "http://localhost:4000"

paginate: 10

markdown: kramdown
permalink: "/:categories/:title"
highlighter: rouge

excerpt_separator: <!--more-->

collections:
  library:
    output: true
  indices:
    output: true

gems:
  - jekyll-sitemap
